### PR TITLE
Remove unnecessary method and interface

### PR DESCRIPTION
**Pull request by wg1j**
1. remove `sort()`
2. remove `Comparable`

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Thank you for this update.

Why do you think this sort is not necessary? And I can confirm, it is not necessary anymore and your changes are perfectly fine.

There was a good reason for that which is not valid anymore. Can you guess it? 😄 

Kind regards
Mahmoud

**Comment by wg1j** [comment]
Hi, 

Sorry for my mistake, it is impolite that creating PR but without explains.

In my opinion:

1.  A `TreeSet` must specify a sort type *(natural ordering, comparator, etc.)* while it be constructed. And it will be compared and sorted when call `add(E e)`  to  insert elements. 
https://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html#TreeSet()

2.  `Rules` API has the same sort type *(`new TreeSet<>()` natural ordering)* with the method `sort()`. Most of the time it is invalid when method `sort()` called by `DefaultRulesEngine` in method `check()` and `fire()`. The only problem is that `Rules` may be not sorted when created with `Rules(Set<Rule> rules) `. 

Thats all. My English is poor,  Can you get me ? 😅

**Comment by benas** [comment]
Hi,

> Sorry for my mistake, it is impolite that creating PR but without explains.

Oh no problem at all! That's fine don't worry.

The reason rules are sorted in each call to `fire` is that it was possible to change their priorities at runtime through JMX. Now that JMX feature is deprecated (issue #47 ), there is no need anymore to (re)sort them every time. Do you see the trick?

I'll merge your PR and include in next release. This will actually improve the performance of the engine.

Thank you!

Kr
Mahmoud

**Comment by wg1j** [comment]
Your explain is brief and to the point. Just does't need (re)sort anymore! 
 Actually, I have not seen in the before. 😂

**Pull request merged**
