### PR TITLE
Removed the listeners added by default to DefaultRulesEngine

### PR DESCRIPTION
**Pull request by ablx**
Hi,
the listeners added by default are to opinionated in my mind (e.g. they use a predefined logger and log on info).
I removed them and made the implementation of the listeners public final, so everyone can added them when needed

### CODE REVIEW

**Comment by benas** [comment]
Hi,

I just saw your message on gitter. Thank you for opening this PR.

This PR basically reverts this commit: 38f13307fcb761785a685a8ffc6d7e89c1129609
These default listeners only add some logging, which was in the the engine anyway. The result is the same. So just to make sure I understand the motivation behind this PR, what's wrong with the default listener?

> the listeners added by default are to opinionated in my mind (e.g. they use a predefined logger and log on info).

It's the SLF4J logger. What do you mean by "predefined" ? You can plug any logging library you want.
In regards to the log level, you can always configure it as you wish.

Kr
Mahmoud

**Comment by tsjoberg** [comment]
+1 for this PR -> I do believe that logging should be up to the app developer (I know its a very opinionated topic). That being said not to say that the default listener could still be in the project with some documentation on how to add it to the rules engine config in case people wanted to use it with the same effect as current implementation - thoughts?

**Comment by ablx** [comment]
What @tsjoberg said :-)

**Comment by benas** [comment]
Hi,

> the listeners added by default are to opinionated in my mind (e.g. they use a predefined logger and log on info).

Let's say we completely remove this `DefaultRuleListener`, the engine's code would be something like:

```java
try {
    triggerListenersBeforeExecute(rule, facts);
    LOGGER.debug("Rule '{}' triggered", rule.getName());
    rule.execute(facts);
    triggerListenersOnSuccess(rule, facts);
    LOGGER.debug("Rule '{}' performed successfully", rule.getName());
} catch (Exception exception) {
    triggerListenersOnFailure(rule, exception, facts);
    LOGGER.error("Rule '" + rule.getName() + "' performed with error", exception);
}
```

Given the fact that `LOGGER` is from slf4j and that I've already changed the default log level to `DEBUG` (See #166 ), can you tell me what would make this opinionated and how does it use a "predefined" logger?

I believe that moving the logging code in a listener gives exactly the same result and makes the code cleaner:

```java
try {
    triggerListenersBeforeExecute(rule, facts);
    rule.execute(facts);
    triggerListenersOnSuccess(rule, facts);
} catch (Exception exception) {
    triggerListenersOnFailure(rule, exception, facts);
}
```

This is what was basically done in 38f13307fcb761785a685a8ffc6d7e89c1129609.

Again, given the fact that all logging is now based on slf4j (See #113 ) and that I've already changed the default log level to `DEBUG` (In #166 ), do you still disagree with the current approach?

Kr,
Mahmoud

**Comment by ablx** [comment]
Closing this since it's not important for me anymore. Feel free to reopen if you think it's still valid

**Pull request closed without merging**
