### PR TITLE
Update UnitRuleGroupTest.java

### PR DESCRIPTION
**Pull request by zhhaojie**
add @Test on UnitRuleGroupTest#compositeRuleMustNotBeExecutedIfAComposingRuleEvaluatesToFalse Method.
new a unitRuleGroup Object in the test case to avoid NPE .

### CODE REVIEW

**Comment by benas** [comment]
@zhhaojie Good catch! That moment when you discover a test method not annotated with `@Test` 😄  Thank you for the PR.

However, I consider `when(rule2.evaluate(facts)).thenReturn(false);` to be part of the "Arrange" phase (so in the "given" block in our case), even though mockito's method is called `when`.

**Comment by zhhaojie** [comment]
> @zhhaojie Good catch! That moment when you discover a test method not annotated with `@Test` 😄
> 
> However, I consider `when(rule2.evaluate(facts)).thenReturn(false);` to be part of the "Arrange" phase (so in the "given" block in our case), even though mockito's method is called `when`.
> 
> I added you to the contributors list. Thank you for the PR!

yes, that's my fault .I misunderstood your intentions.

**Comment by zhhaojie** [comment]
> @zhhaojie Good catch! That moment when you discover a test method not annotated with `@Test` 😄
> 
> However, I consider `when(rule2.evaluate(facts)).thenReturn(false);` to be part of the "Arrange" phase (so in the "given" block in our case), even though mockito's method is called `when`.
> 
> I added you to the contributors list. Thank you for the PR!

yes, that's my fault .I misunderstood your intentions. 
i am using `easy-rules` And `easy-flows` on our company risk-control-system project.
so so so appreciate your great job!

**Comment by benas** [comment]
Oh great! Glad to hear that! If you need support, I would love to help.

**Pull request merged**
