### PR TITLE
Improve the handling of rules engine subclasses

### PR DESCRIPTION
**Pull request by spearway**
This should enable better subclassing of the rule engine. 

Existing code should only see an added warning and no breakage (see unit test).

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Thank you for your PR and corresponding tests.

It is impossible to subclass `DefaultRulesEngine` class, it is package private by design.
You were able to extend it because your test class is in the same package as `DefaultRulesEngine`. In practice, this would not happen. 

But let's imagine I decide to create my own implementation of `RulesEngine` interface, to load rules from an xml file which I pass to constructor for instance:

```java
class XMLRulesEngine implements RulesEngine {

   public XMLRulesEngine(File rules, RulesEngineParameters parameters, List<RuleListener> listeners){
      ...
   }

}
```

Do you think this new generic builder can instantiate my class? Looking at what the `build` method is expecting, I think it will fail.

But the question is why would I use this new generic builder anyway? I may create a builder for my `XMLRulesEngine` which may have totally different set of parameters and others configuration options. Do you agree?

Kind regards
Mahmoud

**Comment by spearway** [comment]
Why do you think that the default implementation should be package private? I really don't see the point of having to reimplements all the method of the interface if I need to change the behaviour a little. This would be similar to the AbstractList in java.

**Comment by benas** [comment]
> Why do you think that the default implementation should be package private? I really don't see the point of having to reimplements all the method of the interface if I need to change the behaviour a little. 

You want to change the behaviour of the engine. This is what we *don't* want, and that's why it was intended to make it closed for modifications (We can make it public, but it will be final in this case).
We don't want clients to subclass it and change its behaviour after it was tested.
The engine is open for extension through listeners and configurable using parameters.

What would you like to modify a little? May be we can make this behaviour configurable?

> I agree that we have the limitation of having a standard constructor.

Not only a default constructor, but a constructor with exactly the same signature as `DefaultRulesEngine`, with this check:

`if ((parameters.length == 2) && RulesEngineParameters.class.isAssignableFrom(parameters[0]) && List.class.isAssignableFrom(parameters[1]))`

Meaning the builder will fail to create my `XmlRulesEngine` even if I add a default constructor.

> This would be similar to the AbstractList in java.

Not really. If you want a perfect analogy,  It would be making ArrayList package private, having a ListBuilder that returns a List of type ArrayList.

But in this case, what you are suggesting in this PR, is having a generic ListBuilder taking as parameter the list type and then create it with reflexion:

```java
private ListBuilder(Class<E extends List> listClass) {
 ...
}

//and  throw ListInstantiationException in the build method if not able to create an instance of the desired list type
```

Meaning as a user of this builder, I would write something like:

```
List<String> strings = new ListBuilder<>(ArrayList.class).build();

// or for my slightly different custom implementation of ArrayList
List<String> strings = new ListBuilder<>(MyArrayList.class).build();
```

Do you think is how we should build custom lists with a generic builder via reflexion?

**Comment by benas** [comment]
Hi @spearway ,

The `DefaultRulesEngine` class has been made public starting from v3. But it is final because as explained, we don't want people to extend it and modify it after it has been tested.

In regards to the generic builder suggestion of this PR, there will be multiple implementations of the `RulesEngine` interface (default, forward chaining, backward chaining, rete, etc). Each engine will have its own set of parameters which are different from other engines. Hence, each engine may have its own builder (if any) and the idea of a generic builder will have no real added value in the end.

For this reason, I'm closing this PR.
Thank you for your time! Hope you understand this decision.

Kind regards
Mahmoud

**Pull request closed without merging**
