### PR TITLE
Override equals()/hashCode()/toString() same as BasicRule

### LINKED ISSUE #100: RuleProxy invoke with equals get an unexpected result
Hi, 

Here is my code:

```java
@org.jeasy.rules.annotation.Rule
class DummyRule {
    @Condition
    public boolean when() { return true; }

    @Action
    public void then() { }
}

@Test
public void invokEquals() {
    Object rule = new DummyRule();
    Rule proxy1 = RuleProxy.asRule(rule);
    Rule proxy2 = RuleProxy.asRule(proxy1);
  
    assertTrue(proxy1.equals(rule));
    assertTrue(proxy1.equals(proxy1));
    assertTrue(proxy1.equals(proxy2));
}
```

I expected to `false true true`, but the actual is `true false false`. It is totally unexpected that the result of  `proxy1.equals(proxy1)` is **`false`**. 

I check the `equals()` defined in [javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)) :

>   **It is *reflexive*: for any non-null reference value `x`, `x.equals(x)` should return `true`.**
>
>   It is *symmetric*: for any non-null reference values `x` and `y`, `x.equals(y)` should return `true` if and only if `y.equals(x)` returns `true`.
>
>   It is *transitive*: for any non-null reference values `x`, `y`, and `z`, if `x.equals(y)` returns `true` and `y.equals(z)` returns `true`, then `x.equals(z)` should return `true`.
>
>   It is *consistent*: for any non-null reference values `x` and `y`, multiple invocations of `x.equals(y)` consistently return `true` or consistently return `false`, provided no information used in `equals` comparisons on the objects is modified.
>
>   For any non-null reference value `x`, `x.equals(null)` should return `false`.

Furthermore, `equals()` always relate to `hashCode()`, and may have influenced to hash-based **`Collection`** or **`Map`**.

Thus,  what do you think about  to override `equals()` and `hashCode()`?, and how to do it?

### PR DESCRIPTION
**Pull request by wg1j**
fix #100

### CODE REVIEW

**Comment by wg1j** [comment]
Hi,
There  are 9 method conditions need to invoke, so statement `switch` will have  better performance and  clearer code.

**Comment by benas** [comment]
Hello,

That's fantastic! the code is definitely more readable and has better performance.

One question though, why did you choose to use an enum for the switch instead of String? Java 7 supports String in switch. Is there a reason for that?

I've sent you an invitation to join the core team. You are a great contributor and I would like to give you full access to easy rules. You are welcome if you want! 

Many thanks for all your efforts to improve easy rules 👍 

Kr
Mahmoud

**Comment by wg1j** [comment]
Thanks for your invitation, it's a great pleasure to join your.Thank you so so much! 

Actually as we know, Strings in switch Statements is a `Syntactic sugar`, it works with `equals()` and `hashCode()`, I'll show your an example:

**Source Code**

```java
switch (method.getName()) {
    case "getName" :
        System.out.println(method.getName());
        break;
    case "getDescription" :
        System.out.println(method.getName());
        break;
    case "getPriority" :
        System.out.println(method.getName());
        break;
    default:
        break;
}
```

**Compiled in JDK8 and Decompile by IntelliJ IDEA **

```java
String var4 = method.getName();
byte var5 = -1;
switch(var4.hashCode()) {
case -75308287:
    if (var4.equals("getName")) {
        var5 = 0;
    }
    break;
case 912439066:
    if (var4.equals("getPriority")) {
        var5 = 2;
    }
    break;
case 1930152646:
    if (var4.equals("getDescription")) {
        var5 = 1;
    }
}

switch(var5) {
case 0:
    System.out.println(method.getName());
    break;
case 1:
    System.out.println(method.getName());
    break;
case 2:
    System.out.println(method.getName());
}
```

As you see, it still works with the `byte` and `int`. But with `enum` Java compiler doesn't nedd do that. So I think `enum` is more friendly to compiler.

**Comment by benas** [comment]
Thank you for the example and welcome onborad!

> So I think enum is more friendly to compiler.

To be honest, I don't care about the compiler, really. We write code that is easier for humans to understand, not to help the compiler. The compiler is there to help us, not the other way around 😄

Method name is a String, so it is easier for a human to compare it to a string directly than to an enum and do the enum to String mapping in his head. Do you agree? IMO, the introduction of String in switch was designed for exaclty for this.

**Comment by wg1j** [comment]
Ok, your are right, I''' fix it later. 😀

**Comment by wg1j** [comment]
Hi @benas,
I have fixed it. It is simpler, clearer and easier to understand now. 😀

**Comment by benas** [comment]
Fantastic! Thank you this yet another great contribution 👍

**Pull request merged**
