### PR TITLE
[safe-condition]: Safe evaluation. Do not throws exception

### PR DESCRIPTION
**Pull request by sanmibuh**
Actual process of DefaultRulesEngine:
- Evaluate method is not error safe
- Execute method is error safe

If any rule evaluation fails and launch an exception, the engine throws an exception. If we have a complex evaluation, an exception could be thrown.

This PR avoids this problem. 

Plus added onEvaluateFailure listener for this case.

### CODE REVIEW

**Comment by benas** [comment]
Hi,

It was intented to make the `evaluate` method return a boolean and not throw an exception.
The user should handle any exception and return true/false accordingly.

In contrast, the `execute` method was designed to throw an exception and let the engine handle it according to some configurable strategy (skipping next rules, ignore the error, etc).

The only case where an exception could be thrown in the `evaluate` method is when a fact is missing. To be honest, this is a design mistake from my part. It could be better to make the proxy log a warning on the missing fact and return false (instead of throwing a `NoSuchFactException` and adding a `skipOnMissingFact` parameter). This should be fixed in a future version. Do you see?
I tried to explain my thoughts about this [here](https://gitter.im/j-easy/easy-rules?at=5935246e142826e972845881), but I would to rechallenge these thoughts 😄 

That said, if we fix this behaviour, I'm not sure we should make the `evaluate` method throw an exception and intercept the evaluation error in the listener. Do you agree?

Kr
Mahmoud

**Comment by sanmibuh** [comment]
Hello,
Imagine that any fact is a complex object. Maybe the evaluate method can throw any RuntimeException. In this case the rulesEngines will throw the exception, breaking the execution.

In execute method, this use case is safe

Maybe this line should catch only RuntimeException
https://github.com/j-easy/easy-rules/pull/112/files#diff-b55e6fd77e7ad5c46132938da8cd5e5dR165

Best,

**Comment by benas** [comment]
Hello,

Yes I understand. But regardless of how complex the logic of the evaluate method is, the user has to catch any exception (including runtime ones if they may occurs) and return true/false accordingly. May be this should be specified in the Javadoc.

The contract of the `evaluate` method is clear, it is not intended to throw an exception. So any error handling is done by the user. Same for `execute`, it decalres that it may throw an exception, so the user can delegate error handling to the engine.

Today, the evaluate method may throw a runtime exception when a fact is missing, and as I said, this is a mistake and I'll fix it in v3.1.

Best regards
Mahmoud

**Comment by sanmibuh** [comment]
Yes, I see your changes to capture **NoSuchFactException**.

This PR only enlarges this feature, catching all Exceptions (should be better catching only RuntimeException).
As it already exists a try/catch, there is no overhead catching also **RuntimeException**. And this feature avoids us to catch RuntimeException on every Rules **evaluation** methods.

Best,

**Comment by sanmibuh** [comment]
Rebased and modified catch on **evaluate** to catch only RunTimeExceptions

**Comment by benas** [comment]
Thank you for the update.

I'm currently fixing the `skipOnMissingFact` param which is a mistake a think (it's good it is not released yet 😄). If a declared fact is missing, the rule should simply not be triggered (as suggested [here(https://gitter.im/j-easy/easy-rules?at=5934709dca6d4ae80cdf3a45)]).

The `evaluate` method will not throw any runtime exception (and if the user's code may throw a runtime exception, the user must handle this and not the engine) and we will have the "safe evaluation". In that case, I'm not sure this PR is relevant anymore (there is nothing to say about the quality of the PR, but more about its added value after this fix).

**Comment by benas** [comment]
Hi @sanmibuh 

I've removed the `skipOnMissingFact` parameter. Now the rule proxy returns false when a fact is missing. I will update the documentation to state that error handling should be done by the client code (even though it can be deduced from the method signature).

As discussed previously, I'm closing this PR since it has no added value after the fix.
Thank you for your time and effort!

Kr
Mahmoud

**Comment by benas** [comment]
> I will update the documentation to state that error handling should be done by the client code

doen here: 0267ba397c39ad3affbfb29df4fce314c405ceaa

**Pull request closed without merging**
